import pandas as pd

df = pd.read_excel(
    "/home/sunx/data/aiiih/projects/sunx/projects/CIED/Database 6.12 clean LB.xlsx"
)

# Column types
demo = ["Age", "Sex (1-M)", "Height cm", "Weight Kg", "BMI"]
disease = [
    "HF (1=Y)",
    "HTN (1=Y)",
    "CAD",
    "MI (Y=1)",
    "VT/VF",
    "Vfib (1=Y)",
    "VT (1=Y)",
    "Afib (1=Y)",
    "CKD (1=Y)",
]
device_info = [
    "Type of Device (ICD =1 PPM = 2 CRT = 3)",
    "ICD indication (Primary prevention = 1, secodary prevention =2)",
    "PPM indications (CHB = 1, SND = 2, Other = 3)",
    "MR Conditional ",
    "Position in body (left chest = 1, right chest = 2, leadless = 3, 4=subC)",
    "Position (L chest=1, other=2)",
    "Manufacturer (1=Boston,2=MDT,3=Bio,4=StJude,5=other)",
    "Atrial Lead Yes/No",
    "Ventricular lead Yes/No",
    "SubQ lead - (0=no,1=yes,3=other (leadless)",
    "LV lead Yes/No",
]
device_position = [
    "Rotation. 0 = normal, 1 rotated.",
    "PPM to RV Lead",
    "PPM to LV Lead",
    "PPM to subQ (can to subQ lead)",
    "CXR- PPM to cardiac silhouette - shortest (mm)",
    "PPM to LV Apex",
    "Widest Chest Transverse Diameter",
    "Lat view- Inf edge of PPM to RV lead tip",
    "Lat view- Inf edge of PPM to LV lead tip",
    "Lat view- Inf edge of PPM to SubQ lead tip",
]
label = [
    "Pre-MR diagnosis/suspected_simplified (1=infiltrative,2=valvulopathy,3=HOCM,4=myopericarditis,5=ischemia,6=other unexplained CMP,7=Othe, 8= VT)",
    "Post-MR diagnosis/suspected_simplified (1=infiltrative,2=valvulopathy,3=HOCM,4=myopericarditis,5=ischemia,6=other unexplained CMP,7=Othe, 8= VT)",
    "Non-diagnostic",
    "Did the patients’ suspected diagnosis change post MR",
    "Did MRI provide additional information to the existing diagnosis? (ie quantity of iron, location of scar, etc) ",
    " Was the pre-MRI (tentative) diagnosis confirmed?",
    "Was patient management altered as a result of the scan data?",
]
tfe = [
    "TFE (exact sequence listed)",
    "Any artefact (grade 3 or above)",
    "Artefact ratio (biventricular)",
    "B_Anterior",
    "B_Anterolateral",
    "B_Inferolateral",
    "B_Inferior",
    "B_Inferoseptal",
    "B_Anteroseptal",
    "M_Anterior",
    "M_Anterolateral",
    "M_Inferolateral",
    "M_Inferior",
    "M_Inferoseptal",
    "M_Anteroseptal",
    "A_Anterior",
    "A_Lateral",
    "A_Inferior",
    "A_Septal",
    "RV_Base",
    "RV_Mid",
    "RV_Apex",
    "Cause of Artifact (1=IPG, 2=Lead, 3=Both, 0=None)",
    "RV Artefact cause (Lead alone=1, lead and device=2, neither=3,IPG=4)",
]
cine_ssfp = [
    "CINE_SSFP (exact sequence listed)",
    "Any artefact (grade 3 or above).1",
    "Artefact ratio (biventricular).1",
    "B_Anterior.1",
    "B_Anterolateral.1",
    "B_Inferolateral.1",
    "B_Inferior.1",
    "B_Inferoseptal.1",
    "B_Anteroseptal.1",
    "M_Anterior.1",
    "M_Anterolateral.1",
    "M_Inferolateral.1",
    "M_Inferior.1",
    "M_Inferoseptal.1",
    "M_Anteroseptal.1",
    "A_Anterior.1",
    "A_Lateral.1",
    "A_Inferior.1",
    "A_Septal.1",
    "RV_Base.1",
    "RV_Mid.1",
    "RV_Apex.1",
    "Cause of Artifact (1=IPG, 2=Lead, 3=Both, 0=None).1",
    "RV Artefact cause (Lead alone=1, lead and device=2, neither=3, IPG=4)",
]
viab = [
    "VIAB (exact sequence listed)",
    "Any artefact (grade 3 or above).2",
    "Artefact ratio (biventricular).2",
    "B_Anterior.2",
    "B_Anterolateral.2",
    "B_Inferolateral.2",
    "B_Inferior.2",
    "B_Inferoseptal.2",
    "B_Anteroseptal.2",
    "M_Anterior.2",
    "M_Anterolateral.2",
    "M_Inferolateral.2",
    "M_Inferior.2",
    "M_Inferoseptal.2",
    "M_Anteroseptal.2",
    "A_Anterior.2",
    "A_Lateral.2",
    "A_Inferior.2",
    "A_Septal.2",
    "RV_Base.2",
    "RV_Mid.2",
    "RV_Apex.2",
    "Breathing artifact (No=0, Yes=1)",
    "Cause of Artifact (1=IPG, 2=Lead, 3=Both, 0=None).2",
    "RV Artefact cause (Lead alone=1, lead and device=2, neither=3, IPG=4).1",
]
